// packages/ui/core/src/app/modules/accept-invitation/accept-invitation.component.ts
import { UiCommonModule, UserInvitationService } from '@activepieces/ui/common';
import { ChangeDetectionStrategy, Component, OnInit } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { Observable, catchError, map, of, switchMap, tap } from 'rxjs';

@Component({
  selector: 'app-accept-invitation',
  templateUrl: './accept-invitation.component.html',
  styleUrls: [],
  changeDetection: ChangeDetectionStrategy.OnPush,
  standalone: true,
  imports: [UiCommonModule],
})
export class AcceptInvitationComponent implements OnInit {
  acceptInvitation$: Observable<void> | undefined;
  invalidToken = false;

  constructor(
    private activatedRoute: ActivatedRoute,
    private router: Router,
    private userInvitationService: UserInvitationService
  ) {}

  ngOnInit(): void {
    this.acceptInvitation$ = this.activatedRoute.queryParams.pipe(
      switchMap((query) => {
        return this.userInvitationService.accept({
          invitationToken: query['token'],
        });
      }),
      tap((value) => {
        if (!this.invalidToken) {
          if (!value.registered) {
            this.redirectToSignUp();
          } else {
            this.router.navigate(['/sign-in']);
          }
        }
      }),
      map(() => undefined),
      catchError((e) => {
        console.error(e);
        this.invalidToken = true;
        return of(undefined);
      })
    );
  }

  redirectToSignUp() {
    // Add any necessary logic before redirecting, if needed
    setTimeout(() => {
      const email = this.activatedRoute.snapshot.queryParamMap.get('email');
      this.router.navigate(['/sign-up'], { queryParams: { email } });
    }, 3000);
  }
}

<div class="ap-container ap-mx-auto ap-mt-10 ap-max-w-md">
  <ng-container *ngIf="!invalidToken">
    <p class="ap-text-2xl ap-font-bold ap-text-center" i18n>
      Team Invitation Accepted
    </p>
    <p class="ap-mt-4 ap-text-lg ap-text-center ap-text-gray-700" i18n>
      Thank you for accepting the invitation. We are redirecting you right
      now...
    </p>
  </ng-container>
  <ng-container *ngIf="invalidToken">
    <p class="ap-mt-4 ap-text-lg ap-text-center ap-text-red-500" i18n>
      Invalid invitation token. Please try again.
    </p>
  </ng-container>
</div>

<ng-container *ngIf="acceptInvitation$ | async"></ng-container>

// packages/react-ui/src/features/team/component/accept-invitation.tsx
import { useMutation } from '@tanstack/react-query';
import { useEffect, useState } from 'react';
import { useNavigate, useSearchParams } from 'react-router-dom';

import { userInvitationApi } from '../lib/user-invitation';

import { LoadingSpinner } from '@/components/ui/spinner';
const AcceptInvitation = () => {
  const [isInvitationLinkValid, setIsInvitationLinkValid] = useState(true);
  const navigate = useNavigate();
  const [searchParams] = useSearchParams();
  const { mutate, isPending } = useMutation({
    mutationFn: async (token: string) => {
      const { registered } = await userInvitationApi.accept(token);
      return registered;
    },
    onSuccess: (registered) => {
      setIsInvitationLinkValid(true);
      if (!registered) {
        setTimeout(() => {
          const email = searchParams.get('email');
          navigate(`/sign-up?email=${email}`);
        }, 3000);
      } else {
        navigate('/sign-in');
      }
    },
    onError: () => {
      setIsInvitationLinkValid(false);
    },
  });
  useEffect(() => {
    const invitationToken = searchParams.get('token');
    if (!invitationToken) {
      setIsInvitationLinkValid(false);
      return;
    }
    mutate(invitationToken);
  }, [mutate, searchParams]);

  return isPending ? (
    <div className="w-screen h-screen flex justify-center items-center">
      <LoadingSpinner size={50}></LoadingSpinner>
    </div>
  ) : (
    <div className="container mx-auto mt-10 max-w-md">
      {isInvitationLinkValid ? (
        <>
          <p className="text-2xl font-bold text-center">
            Team Invitation Accepted
          </p>
          <p className="mt-4 text-lg text-center text-gray-700">
            Thank you for accepting the invitation. We are redirecting you right
            now...
          </p>
        </>
      ) : (
        <p className="mt-4 text-lg text-center text-red-500">
          Invalid invitation token. Please try again.
        </p>
      )}
    </div>
  );
};
AcceptInvitation.displayName = 'AcceptInvitation';
export { AcceptInvitation };
