// packages/ee/project-members/src/lib/accept-invitation/accept-invitation.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { ProjectMemberService } from '../service/project-members.service';
import { Observable, catchError, map, of, switchMap, tap } from 'rxjs';

@Component({
  selector: 'app-accept-invitation',
  templateUrl: './accept-invitation.component.html',
  styleUrls: [],
})
export class AcceptInvitationComponent implements OnInit {
  acceptInvitation$: Observable<void> | undefined;
  invalidToken = false;

  constructor(
    private activatedRoute: ActivatedRoute,
    private router: Router,
    private projectMemberService: ProjectMemberService
  ) {}

  ngOnInit(): void {
    this.acceptInvitation$ = this.activatedRoute.queryParams.pipe(
      switchMap((query) => {
        return this.projectMemberService.accept({
          token: query['token'],
        });
      }),
      tap((value) => {
        if (!this.invalidToken) {
          if (!value.registered) {
            this.redirectToSignUp();
          } else {
            this.router.navigate(['/sign-in']);
          }
        }
      }),
      map(() => undefined),
      catchError((e) => {
        console.error(e);
        this.invalidToken = true;
        return of(undefined);
      })
    );
  }

  redirectToSignUp() {
    // Add any necessary logic before redirecting, if needed
    setTimeout(() => {
      const email = this.activatedRoute.snapshot.queryParamMap.get('email');
      this.router.navigate(['/sign-up'], { queryParams: { email } });
    }, 3000);
  }
}

<div class="ap-container ap-mx-auto ap-mt-10 ap-max-w-md">
    <ng-container *ngIf="!invalidToken;">
        <p class="ap-text-2xl ap-font-bold ap-text-center" i18n>
            Team Invitation Accepted
          </p>
          <p class="ap-mt-4 ap-text-lg ap-text-center ap-text-gray-700" i18n>
            Thank you for accepting the invitation. We are redirecting you right now...
          </p>
    </ng-container>
    <ng-container *ngIf="invalidToken;">
      <p class="ap-mt-4 ap-text-lg ap-text-center ap-text-red-500" i18n>
        Invalid invitation token. Please try again.
      </p>
    </ng-container>
  </div>


  <ng-container *ngIf="acceptInvitation$ | async"></ng-container>

// packages/react-ui/src/features/members/component/accept-invitation.tsx
import { useMutation } from '@tanstack/react-query';
import { HttpStatusCode } from 'axios';
import { t } from 'i18next';
import { useEffect, useState } from 'react';
import { useNavigate, useSearchParams } from 'react-router-dom';

import { LoadingSpinner } from '@/components/ui/spinner';

import { api } from '../../../lib/api';
import { userInvitationApi } from '../lib/user-invitation';
import { internalErrorToast } from '@/components/ui/sonner';

const AcceptInvitation = () => {
  const [isInvitationLinkValid, setIsInvitationLinkValid] = useState(true);
  const navigate = useNavigate();
  const [searchParams] = useSearchParams();
  const { mutate, isPending } = useMutation({
    mutationFn: async (token: string) => {
      const { registered } = await userInvitationApi.accept(token);
      return registered;
    },
    onSuccess: (registered) => {
      setIsInvitationLinkValid(true);
      if (!registered) {
        setTimeout(() => {
          const email = searchParams.get('email');
          navigate(`/sign-up?email=${email}`);
        }, 3000);
      } else {
        navigate('/sign-in');
      }
    },

    onError: (error) => {
      setIsInvitationLinkValid(false);
      if (api.isError(error)) {
        switch (error.response?.status) {
          case HttpStatusCode.InternalServerError: {
            console.log(error);
            internalErrorToast();
            break;
          }
          default: {
            break;
          }
        }
      }
    },
  });
  useEffect(() => {
    const invitationToken = searchParams.get('token');
    if (!invitationToken) {
      setIsInvitationLinkValid(false);
      return;
    }
    mutate(invitationToken);
  }, [mutate, searchParams]);

  return isPending ? (
    <div className="w-screen h-screen flex justify-center items-center">
      <LoadingSpinner isLarge={true}></LoadingSpinner>
    </div>
  ) : (
    <div className="container mx-auto mt-10 max-w-md">
      {isInvitationLinkValid ? (
        <>
          <p className="text-2xl font-bold text-center">
            {t('Team Invitation Accepted')}
          </p>
          <p className="mt-4 text-lg text-center text-gray-700">
            {t(
              'Thank you for accepting the invitation. We are redirecting you right now...',
            )}
          </p>
        </>
      ) : (
        <p className="mt-4 text-lg text-center text-red-500">
          {t('Invalid invitation token. Please try again.')}
        </p>
      )}
    </div>
  );
};
AcceptInvitation.displayName = 'AcceptInvitation';
export { AcceptInvitation };
